config/routes.rb
Rails.application.routes.draw do
  get 'cover/report'

  devise_for :users
  root 'cover#report'
  get 'home/mypage_mail_archive'
  get 'home/mypage_scrap_archive'
  get 'home/mypage_community_archive'
   get 'home/mypage_reply_archive'
  post 'liking/:form_id' => 'home#liking', as: 'liking'
  post 'home/form_scrap_action'
  delete 'home/form_scrap_action'
  get 'home/firstpage'
  get 'home/firstpage_result'
  get 'cover/contact'
  get 'home/form_write'
  post 'home/form_action'
  get 'form_destroy/:form_id' => "home#form_destroy", as: "form_destroy"
  get 'form_reply_destroy/:reply_id' => "home#form_reply_destroy", as: "form_reply_destroy"  
  get 'form_update/:form_id' => "home#form_update", as: "form_update"
  post 'form_update_action/:form_id' => "home#form_update_action"
  post 'home/form_reply'
  get 'home/form_result'
  get 'form_mail/:form_id' => "home#form_mail", as: "form_mail"
  post 'form_m_update/:form_id' => "home#form_m_update"
  get 'home/post_write'
  post 'post_action' => "home#post_action"
  get '/post_view/:post_id' => "home#post_view"
  get 'home/post_reply'
  post 'home/post_reply'
  get 'post_view/:post_id' => "home#post_view", as: "post_view"
  get 'post_destroy/:post_id' => "home#post_destroy", as: "post_destroy" 
  get 'post_reply_destroy/:reply_id' => "home#post_reply_destroy"  
  get 'post_update/:post_id' => "home#post_update", as: "post_update"
  post 'post_update_action/:post_id' => "home#post_update_action"
  get 'home/post_result'
  get 'home/mypage'
  
  get '/firstpage', to: 'home#firstpage'
  get '/form_list/:category', to: 'home#form_list', as: "form_list"

  get '/form_view/:form_id', to: 'home#form_view', as: "form_view"
  get '/post_list', to: 'home#post_list', as: "post_list"

  devise_for :users, :skip => [:sessions]
  as :user do
    get 'signin' => 'devise/sessions#new', :as => :home_firstpage_path
  end

end

app/controllers/home_controller.rb
require 'mailgun'
class HomeController < ApplicationController
  before_action :authenticate_user!
  impressionist :actions => [:show]
  
  #마이페이지 입니다.
  def mypage
     @forms=Form.where(writer: current_user).take(3).reverse
     @posts=Post.where(writer: current_user).take(3).reverse
     @scraps=Scrap.where(writer: current_user).take(3).reverse
     @reply_forms=Freply.where(writer: current_user).take(3).reverse
    
    
  end
  
  #내가 쓴 메일 양식 보관함
  def mypage_mail_archive 
    @forms=Form.where(writer: current_user).reverse
  end
  
  #내가 쓴 커뮤니티 게시글
  def mypage_community_archive
    @posts=Post.where(writer: current_user).reverse
  end
  
  #내가 스크랩한 글
  def mypage_scrap_archive
    @scraps=Scrap.where(writer: current_user).reverse
  end
  def mypage_reply_archive
    @reply_forms=Freply.where(writer: current_user).reverse
  end
  
  def firstpage
    @forms = Form.all
    @posts = Post.all
  end
  def firstpage_result
    
    if params[:search]
      @forms = Form.search(params[:search]).reverse
      @posts = Post.search(params[:search]).reverse
    else
    end
  end
  
  # 메일 양식 작성
  def form_write
  end
  
  # 메일 양식 작성 액션
  def form_action
    #writer: params[:nickname]추가예정
    form = Form.create
    form.writer = current_user
    form.category = params[:category]
    form.title = params[:title]
    form.content = params[:content]
    form.hashtag = params[:hashtag]
    form.save
    
    redirect_to "/form_list/" + params[:category]
  end
  
  def liking
    @forming = Form.find(params[:form_id])
    if @forming.likers.include? current_user
      @forming.likers.delete(current_user)
    else
      @forming.likers << current_user
    end
  end
  
  # 메일 양식 리스트 출력
  def form_list
    @forms = Form.where(category: params[:category]).reverse
    @best_form = @forms.sort_by{|b| b.likers.count}.reverse.take(3)
   
    
    Freply.all
  end
  
  # 작성된 하나하나의 메일 양식 & 댓글 출력 
  def form_view
    @view_form = Form.find(params[:form_id])
    @current_scrap = Scrap.where(writer_id: current_user.id, scrap_id: @view_form.id).first
    impressionist(@view_form)
    Freply.all
  end
  
  def form_destroy
    @one_form = Form.find(params[:form_id]) 
    authorize! :manage, @one_form
    @one_form.destroy
    redirect_to "/form_list/1"
  end
  
  def form_update
    @one_form = Form.find(params[:form_id])
    authorize! :manage, @one_form
  end
  
  def form_update_action
    @one_form = Form.find(params[:form_id]) 
    @one_form.title= params[:title] 
    @one_form.content = params[:content]
    @one_form.hashtag = params[:hashtag]
    @one_form.save
    redirect_to "/form_view/"+params[:form_id] 
  end
  
  # 양식에 대한 댓글 작성 action
  def form_reply
    freply = Freply.new(content: params[:reply_f], form_id: params[:id_of_form], writer: current_user)
    freply.save
    redirect_to "/form_view/" + params[:id_of_form]
    
    
  end
  
  def form_reply_destroy
    
    @reply_form = Freply.find(params[:reply_id])
    authorize! :manage, @reply_form
    @reply_form.destroy
    redirect_to :back  
  end
  
  def form_scrap_action
    if request.post?
      begin
        scrap = Scrap.create(
          title: params[:scrap_title],
          nickname: params[:scrap_nickname],
          time: params[:scrap_time],
          likes: params[:scrap_likes],
          hits: params[:scrap_hits],
          replies: params[:scrap_replies],
          scrap_id: params[:scrap_id],
          writer: current_user
        )
        render :json => { :success => true, :id => scrap.id }
      rescue Exception => e
        render :json => { :success => false, :params => params.inspect }
      end
    elsif request.delete?
      begin
        scrap = Scrap.find_by_id(params[:id])
        if scrap.nil?
          render :json => { :success => false }
        else 
          scrap.destroy
          render :json => { :success => true }
        end
      rescue Exception => e
        render :json => { :success => false, :params => params.inspect }
      end
    end
  end

  
  #해시태그만들기1
  def form_result
    @forms = Form.search(params[:search]).reverse
  end
  
  #메일보내기
  
  def form_mail
    @one_form = Form.find(params[:form_id])
  
  end
  
  def form_m_update
    @receiver = params[:receiver]
    mg_client = Mailgun::Client.new("key-f6f12a06f7725629b847ba47b4b04815")
    
    message_params =  {
                       from: current_user.email,
                       to:   @receiver,
                       subject: params[:title],
                       text:    params[:content]
                      }
    
    result = mg_client.send_message('sandbox41ceb00888d0479096b32609df172ab0.mailgun.org', message_params).to_h!
    
    message_id = result['id']
    message = result['message']

    @one_form = Form.find(params[:form_id])
    
  
    
    redirect_to "/form_view/"+params[:form_id]
  
  end
  
  # 커뮤니티 게시판 글 작성
  def post_write
    #@posts_title = Post.all
  end
  
  #게시판 글 작성 액션
  def post_action
    post = Post.new
    post.title = params[:title]
    post.content = params[:content]
    post.writer = current_user
    file = params[:pic]
    uploader = GyometeCommunityUploader.new
    uploader.store!(file)
    post.image_url = uploader.url
   
    post.save
    
    redirect_to "/post_list"  
  end
  
  # 커뮤니티 게시판 리스트 출력
  def post_list
    @posts = Post.all.reverse  
    
  end
  
  # 커뮤니티 게시판 리스트에서 검색했을 때 결과
  def post_result
    @posts = Post.search(params[:search].reverse)
    @posts = Post.search params[:search]
  end
  
  # 커뮤니티 게시판 리스트에서 글 눌렀을 때, 제목과 내용 출력과 댓글 달기
  def post_view
    @view_post = Post.find(params[:post_id])
    impressionist(@view_post)
    Preply.all

  end
  
  def post_destroy
    @one_post = Post.find(params[:post_id]) 
    @one_post.destroy
    redirect_to "/post_list"
  end
  
  def post_update
    @one_post = Post.find(params[:post_id])
  end
  
  def post_update_action
    @one_post = Post.find(params[:post_id]) 
    @one_post.title= params[:title] 
    @one_post.content = params[:content]
    @one_post.save
    redirect_to "/post_list" 
  end
  
  # 커뮤니티 게시판에 대한 댓글 작성 action
  def post_reply
    preply = Preply.new(content: params[:reply_p], post_id: params[:id_of_post], writer: current_user)
    preply.save
    redirect_to "/post_view/" + params[:id_of_post]
  end

#대부분 커뮤니티 참고해봤을때, 댓글은 삭제 기능만 있는 게 많아서 구현 안해놓았습니다.  
  def post_reply_destroy
    
    @reply_post = Preply.find(params[:reply_id])
    #위에 들어갈 id 값이 왜 다 넣어봤는데 안되는 걸까..광광...
    @reply_post.destroy
    redirect_to :back  
  end
  

  def my_info
    
  
  end  
  
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_liker_list.html.erb
  <% unless p.likers.empty? %>


    |&nbsp;<%= p.likers.count %>명이 좋아합니다 
    
  

<% end %>

app/views/home/form_list.erb
<section style="width:80%;height:80%;box-left:20%;">
  
<!--BEST 교메때 시작-->  
  <% a = 0 %>
  <div style="padding-top:100px;" >
    <div align="center" class="link_to_color"><br>
      <%= image_tag asset_path('best.png'),style:"width:25%;",class: 'img-responsive' %><br><br><br>
    </div>
    <%@best_form.each do |p|%>
      <%if p.likers.count != 0 %>
        <div class="row" style="padding:30px 30px 10px 30px;">
          <div id="masonry" class="masonry infinite-scroll">
            <% a = 1 %>
            <div class="col-lg-4 col-md-6 col-sm-6 col-xs-6 col-12 masonry photography travel" style="cursor:pointer;"onclick="location.href='/form_view/<%=p.id%>'">
              <div class="post-article">
                <div class="thumbnail">
                  <%= image_tag asset_path('KakaoTalk_20160828_092045856.png'),style:"width:80%;",class: 'img-responsive' %>
                </div>
                <div class="post-entry">
                  <div class="post-content">
                    <ul class="post-author">
                      <li><a href="javascript:void(0)"><i class="fa fa-user"></i><%=p.writer.nickname%></a></li>
                    </ul>
                    <h5 class="post-title">
                      <%= link_to p.title, form_view_path(p.id) , method: 'get'%>
                    </h5>
                  </div>
                  <div class="post-footer">
                    <ul class="post-link">
                      <li><a >
                        <i class="fa fa-clock-o"></i> <%= p.created_at.strftime("%Y-%m-%d")%>
                      </a></li>
                    </ul><br>
                    <ul class="post-link">
                      <li><a>
                        <i class="glyphicon glyphicon-eye-open"></i>&nbsp;<%= p.impressionist_count%>
                      </a></li>
                    </ul>
                    <ul class="post-link">
                      <li><a href="#">
                        <i class="fa fa-comments-o"></i> <%=p.freplies.count%>
                      </a></li>
                    </ul>
                    <ul class="post-link">
                      <li><a >
                        <i class="glyphicon glyphicon-heart" style="color:#ff6666;"></i>&nbsp;<%=  p.likers.count %> 
                      </a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <%end%>
    <%end%>
    <%if a == 0 %>
      <div align="center">
        <h3>"아직 Best 교메때가 없습니다."</h3>
        <p>베스트 교메때에 도전해보세요!</p>
      </div>
    <%end%>
  </div>
  
  <hr style="background-color:black;">
<!--베스트교메때 끝-->

<!--메일양식logo, 검색창 시작--> 
  <%= image_tag asset_path('mailform.png'),style:"width:10%;margin-top:5%;",class: 'img-responsive' %>
  <div align="right" style="margin-bottom:5%; margin-right:5%;">
    <div class="write">
      <div class="wrap" style="float:right; margin-right:35px; display: inline-block;">
        <form class="search" action="/home/form_result" method="GET" accept-charset="UTF-8">
          <input type="text" name="search"  class="form_control" placeholder="&nbsp;검색하기" style="width:200px;">
          <button name="botton" type="submit" class="searchButton" >
            <span class="glyphicon glyphicon-search"></span>
          </button>
        </form>
      </div>
    </div>
  </div>
<!--메일양식logo, 검색창 끝-->



<!--메일양식card 시작--> 
  <div class="row p60" >
    <div id="masonry" class="masonry infinite-scroll">
      <%@forms.each do |p|%>
        <div class="col-lg-4 col-md-6 col-sm-6 col-xs-6 col-12 masonry photography travel" style="cursor:pointer;"onclick="location.href='/form_view/<%=p.id%>'">
          <div class="post-article">
            <div class="thumbnail">
              <a href="single.html" title="#">
                <%= image_tag asset_path('KakaoTalk_20160828_092045856.png'),style:"width:80%;",class: 'img-responsive' %>
              </a>
            </div>
            <div class="post-entry">
              <div class="post-content">
                <ul class="post-author">
                  <li><a href="javascript:void(0)"><i class="fa fa-user"></i><%=p.writer.nickname%></a></li>
                </ul>
                <h5 class="post-title">
                  <%= link_to p.title, form_view_path(p.id) , method: 'get'%>
                </h5>
              </div>
              <div class="post-footer">
                <ul class="post-link">
                  <li><a >
                    <i class="fa fa-clock-o"></i> <%= p.created_at.strftime("%Y-%m-%d")%>
                  </a></li>
                </ul><br>
                <ul class="post-link">
                  <li><a>
                    <i class="glyphicon glyphicon-eye-open"></i>&nbsp; <%= p.impressionist_count%>
                  </a></li>
                </ul>
                <ul class="post-link">
                  <li><a href="#">
                    <i class="fa fa-comments-o"></i> <%=p.freplies.count%>
                  </a></li>
                </ul>
                <ul class="post-link">
                  <li><a >
                    <i class="glyphicon glyphicon-heart" style="color:#ff6666;"></i>&nbsp;<%=  p.likers.count %> 
                  </a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      <%end%>
    </div>
  </div>
  <div style="margin-left:20%;margin-bottom:5%;padding-right:5%;"align="right">
    <button class="btn-orange" type="submit">
      <i class="glyphicon glyphicon-pencil"></i>
      <%= link_to "양식 올리기", home_form_write_path, method: 'get', :style => "color:#ffffff"%>
    </button>  
  </div>
<!--메일양식card 끝--> 

<section>

app/views/home/form_result.erb
<div align="left"style="margin-bottom:1%;margin-top:10%;margin-left:25%;">
    <h1>양식 검색 결과</h1>
</div>

<div style="margin-left:15%;margin-bottom:5%;padding-right:10%;"align="right">
  <div class="write">
    <div class="wrap" style="float:right; margin-right:35px;">
        <form class="search" action="/home/form_result" method="GET" accept-charset="UTF-8">
  
  
            <input type="text" name="search"  class="form_control" placeholder="&nbsp;검색하기" style="width:200px;">
            <button name="botton" type="submit" class="searchButton" >
                <span class="glyphicon glyphicon-search"></span>
            </button>
        </form>
    </div>
  </div>
</div>

         
          
          
          <div class="row p60" style="margin-left:20%;">
                <div id="masonry" class="masonry infinite-scroll">
          <%@forms.each do |p|%>
                    <div class="col-lg-4 col-md-6 col-sm-6 col-xs-6 col-12 masonry photography travel" style="cursor:pointer;"onclick="location.href='/form_view/<%=p.id%>'">
                        <div class="post-article">
                          <div class="thumbnail">
                        
                          <a href="single.html" title="#">
                               <%= image_tag asset_path('1.jpg'), class: 'img-responsive' %>
                          </a>
                          </div>
                  
                            <div class="post-entry">
                                <div class="post-content">
                                    <ul class="post-author">
                                        <li><a href="javascript:void(0)"><i class="fa fa-user"></i><%=p.writer.nickname%></a></li>
                                    </ul>
                                    <h5 class="post-title">
                                        <%= link_to p.title, form_view_path(p.id) , method: 'get'%>
                                    </h5>
                                </div>
                                <div class="post-footer">
                                    <ul class="post-link">
                                        <li><a >
                                            <i class="fa fa-clock-o"></i> <%= p.created_at.strftime("%Y-%m-%d")%>
                                        </a></li>
                                    </ul><br>
                                    <ul class="post-link">
                                        <li><a>
                                             ಠ <%= p.impressionist_count%>
                                        </a></li>
                                    </ul>
                                    <ul class="post-link">
                                      <li><a href="#">
                                          <i class="fa fa-comments-o"></i> <%=p.freplies.count%>
                                      </a></li>
                                    </ul>
                                    <ul class="post-link">
                                        <li><a >
                                            ♡ <%=  p.likers.count %> 
                                        </a></li>
                                    </ul>
                                
                              
                                </div>
                            </div>
                        </div>
                    </div>
            <%end%>
            </div>
                
            </div>
          


<div style="margin-left:20%;margin-bottom:5%;padding-right:5%;"align="right">
  
  <button class="btn-orange" type="submit">
    <i class="glyphicon glyphicon-pencil"></i>
    <%= link_to "양식 올리기", home_form_write_path, method: 'get', :style => "color:#ffffff"%>
  </button>  
  
</div>

app/views/home/form_view.erb
<div id="wrapper" style="opacity: 1; margin-top:100px;">
  <section id="screen-width" class="col-md-8 col-md-offset-1">
    <div class="post-type-blog single">
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <div class="post-article">
            <div class="post-entry">
              <div class="post-content">
                <div class="link_to_color">
                  <%if @view_form.category == 1%>
                    category | 성적정정
                  <%elsif @view_form.category == 2 %>
                    category | 수강문의
                  <%elsif @view_form.category == 3 %>
                    category | 면담요청
                  <%elsif @view_form.category == 4 %>
                    category | 영어메일
                  <%elsif @view_form.category == 5 %>
                    category | 기타양식
                  <%end%>
                </div>
                <hr>
                <div class="post-title">
                  <h1><%=@view_form.title%></h1>
                </div>
                <br>
                <ul class="post-author">
                  <li>
                    <i class="fa fa-user"></i>
                    <%=@view_form.writer.nickname%>
                  </li>
                  <li>
                    &nbsp;&nbsp;&nbsp;
                    <i class="fa fa-clock-o"></i>
                    <%=@view_form.created_at.strftime("%Y-%m-%d %I:%M:%S")%>
                  </li>
                  &nbsp;&nbsp;&nbsp; 조회수:
                  <%=@view_form.impressionist_count%><br>
                </ul>
                <hr>
                <div style="margin-top:5%; margin-bottom:10%;">
                  <p>
                    <%=@view_form.content%>
                  </p>
                </div><br>
              </div>
              <div class="post-footer">
                <div class="post-tag">
                  <i class="glyphicon glyphicon-tags"></i>&nbsp;
                  <h5>Tag:</h5>
                  <% tags = @view_form.hashtag.split(",")%>
                  <%tags.each do |tag|%>
                    #<%=link_to tag,"/home/form_result?search=#{tag}"%>
                  <%end%>
                </div>

              </div>
              <br>
              <br>
              <div class="row">
                <div class="col-xs-5" style="margin-top:1%;">
                  <i class="glyphicon glyphicon-heart" style="color:red;"></i>
                  <%= link_to liking_path(@view_form.id), class: "link_to_color like_btn #{if current_user.likees.include? p then :liked else :unliked end}", method: 'post', remote: true, id: "like_btn_#{@view_form.id}" do %>
                  좋아요
                  <% end %>
                  <span id="liker_wrap<%= @view_form.id %>">
                   <%= render partial: 'liker_list', locals: {p: @view_form} %>
                  </span>
                </div>
                <div class="col-xs-11 edit" style="margin-top:1%;" align="right">
                  <% if can? :manage, @view_form %>
                    <%=link_to form_update_path(@view_form.id), method: 'get' , class: 'btn btn-outline btn-circle btn-sm grey' do%>
                      <i class="fa fa-edit"></i>edit
                    <%end%>
                    <%=link_to form_destroy_path(@view_form.id), method: 'get' , class: 'btn btn-outline btn-circle btn-sm grey' do%>
                      <i class="fa fa-trash-o"></i>delete
                    <%end%>
                  <%end%>
                  
                  <form class="scrap " action="/home/form_scrap_action" style="display: inline-block;">
                    <% unless @current_scrap.nil? %>
                      <input type="hidden" name="id" value="<%= @current_scrap.id %>">
                    <% end %>
                    <input type="hidden" value="<%=@view_form.title%>" name="scrap_title">
                    <input type="hidden" value="<%=@view_form.writer.nickname%>" name="scrap_nickname">
                    <input type="hidden" value="<%=@view_form.created_at.strftime("%Y-%m-%d")%>" name="scrap_time">
                    <input type="hidden" value="<%=@view_form.likers.count%>" name="scrap_likes">
                    <input type="hidden" value="<%=@view_form.impressionist_count%>" name="scrap_hits">
                    <input type="hidden" value="<%=@view_form.freplies.count%>" name="scrap_replies">
                    <input type="hidden" value="<%=@view_form.id%>" name="scrap_id">
                    <button type="submit" class="<%= "active " unless @current_scrap.nil? %>btn btn-outline btn-circle btn-sm darkyellow">
                      <i class="glyphicon glyphicon-star" aria-hidden="true"></i>&nbsp;즐겨찾기
                    </button>
                  </form>
                  
                  
                  
                  <script>
                    $('form.scrap').on('submit', function(event) {
                      event.preventDefault();
                      $scrapForm = $(this);
                      
                      console.log($scrapForm.find('input[name="id"]'));
                      if($scrapForm.find('input[name="id"]').length) {
                        // Unscrap form
                        console.log('request deletion');
                        $scrapForm.blur();
                        $.ajax({
                          type: 'delete',
                          url: $scrapForm.attr('action'),
                          data: $scrapForm.serialize(),
                          success: function(data) {
                            console.log('Removed');
                            console.log(data);
                            if(data.success) {
                              $scrapForm.find('button[type="submit"]').removeClass('active');
                              $scrapForm.find('input[name="id"]').remove();
                            } else {
                              console.log(data.params);
                              alert('Something went wrong!');
                            }
                          }
                        });
                      } else {
                        // Scrap form
                        console.log('request creation');
                        $scrapForm.blur();
                        $.ajax({
                          type: 'post',
                          url: $scrapForm.attr('action'),
                          data: $scrapForm.serialize(),
                          success: function(data) {
                            console.log('Created');
                            console.log(data);
                            if(data.success&&data.id) {
                              $scrapForm.find('button[type="submit"]').addClass('active');
                              $scrapForm.append($('<input type="hidden" value="'+data.id+'" name="id">'));
                            } else {
                              console.log(data.params);
                              alert('Something went wrong!');
                            }
                          }
                        });
                      }
                    });
                  </script>
                  <%=link_to form_mail_path(@view_form.id), method: 'get', class: 'btn btn-outline btn-circle btn-sm orange' do%>
                    <i class="glyphicon glyphicon-envelope" aria-hidden="true"></i>&nbsp;메일작성
                  <%end%>
                </div>
              </div>
            </div>


            <div class="post-comment" style="margin-top:10%;">
              <div class="comment-title">
                <h2><%=@view_form.freplies.count%> Comments</h2>
              </div>

              <div id="comments">
                <ul>
                  <%@view_form.freplies.each do |r|%>
                    <li class="clearfix">
                      <div class="pull-left avatar">
                        <%= image_tag asset_path('avatar1.jpg'),class: 'img-responsive' %>

                      </div>
                      <div class="comment_right">
                        <div class="comment_info clearfix">
                          <div class="pull-left comment_author">
                            <a href="#">
                              <%=r.writer.nickname%>
                            </a>
                          </div>
                        </div>
                        <p>
                          <%=r.content%>
                        </p>

                      </div>
                      <div class="row">
                        <div class="edit" align="left">
                          <%=r.created_at.strftime("%Y-%m-%d %I:%M:%S" )%>
                        </div>
                        <div class="edit" align="right">
                          <% if can? :manage, r %>
                            <%=link_to "삭제",form_reply_destroy_path(r.id), method: 'get', class:"link_to_color"%>
                              <%end%>
                        </div>
                      </div>
                    </li>
                    <%end%>
                </ul>
              </div>
            </div>
            <div class="post-comment">
              <form id="comment_form" class="row" action="/home/form_reply" method="post">
                <div class="form-group">
                  <p class="help-block text-danger"></p>
                  <input type="hidden" value="<%=@view_form.id%>" name="id_of_form">
                  <textarea name="reply_f" class="form-control" placeholder="댓글을 입력하세요." id="comment" required data-validation-required-message="Please enter a message."></textarea>
                  <div id="success"></div>
                </div>
                <div class="col-lg-12 col-md-12">
                  <button type="submit" class="pull-right confirm_btn">확인</button>
                </div>
              </form>
            </div>
            <div>




              <%=link_to "목록으로 가기", form_list_path(@view_form.category) , method: 'get', style: 'color:#ffffff' %>
                </button>
            </div>
          </div>
        </div>

      </div>
  </section>
  </div>

app/views/home/liking.js.erb
$('#liker_wrap<%= @forming.id %>').html('<%= escape_javascript(render partial: "liker_list", locals: {p: @forming}) %>');
<% if current_user.likees.include? @forming %>
    $('#like_btn_<%= @forming.id %>').removeClass('unliked');
    $('#like_btn_<%= @forming.id %>').addClass('liked');
<% else %>
    $('#like_btn_<%= @forming.id %>').addClass('unliked');
    $('#like_btn_<%= @forming.id %>').removeClass('liked');
<% end %>

app/views/home/mypage_reply_archive.erb
<section id="screen-width" class="col-md-8 col-md-offset-3" style="margin-top:5%;">
  <article id="desktop">
    <div class="row">
        <div class="co1 s12 m11 l11">
          <div class="table-wrapper">
            <div class="main-container">
                <h1>내가 쓴 양식 댓글</h1>
                <br>
                <br>
                <div class="write">
                    <div class="wrap" style="float:right; margin-right:35px;">
                        <form class="search" action="/home/post_result" method="GET" accept-charset="UTF-8">

                            <input type="text" name="search" id="search_keyword" placeholder="검색">
                            <button name="botton" type="submit" class="searchButton" >
                                <span class="glyphicon glyphicon-search"></span>
                            </button>
                        </form>
                    </div>
                </div>
                <br>
                <br>
                <br>
                <br>
                <table class="bordered highlight">
                    <thead>
                        <tr>
                            <th data-field="title">내용</th>
                            <th data-field="author">작성자</th>
                            <th data-field="date">날짜</th>
                            
                        </tr>
                    </thead>
                    <tbody>
                        <% @reply_forms.each do |p| %>
                            <tr>
                                <td>
                                    <%=link_to p.content[0..20], form_view_path(p.form_id), method: 'get', class: 'css_class', style: 'color:#454443' %>
                                    <br>
                                </td>
                                <td>
                                    <%=p.writer.nickname%><br>
                                </td>
                                <td>
                                    <%=p.created_at.strftime("%Y-%m-%d")%><br>
                                </td>
                                
                            </tr>
                        <%end%>
                    </tbody>
                    <tbody>
                    </tbody>    

                </table>
                <br>
                <br>
                <br>
                <br>
                <div class="flickr_pagination">...</div>
            </div>
          </div>    
        </div>
    </div>
  </article>
</section>