config/routes.rb
Rails.application.routes.draw do
  get 'cover/report'

  devise_for :users
  root 'cover#report'
  get 'home/mypage_mail_archive'
  get 'home/mypage_scrap_archive'
  get 'home/mypage_community_archive'
   get 'home/mypage_reply_archive'
  post 'liking/:form_id' => 'home#liking', as: 'liking'
  post 'home/form_scrap_action'
  delete 'home/form_scrap_action'
  get 'home/firstpage'
  get 'home/firstpage_result'
  get 'cover/contact'
  get 'home/form_write'
  post 'home/form_action'
  get 'form_destroy/:form_id' => "home#form_destroy", as: "form_destroy"
  get 'form_reply_destroy/:reply_id' => "home#form_reply_destroy", as: "form_reply_destroy"  
  get 'form_update/:form_id' => "home#form_update", as: "form_update"
  post 'form_update_action/:form_id' => "home#form_update_action"
  post 'home/form_reply'
  get 'home/form_result'
  get 'form_mail/:form_id' => "home#form_mail", as: "form_mail"
  post 'form_m_update/:form_id' => "home#form_m_update"
  get 'home/post_write'
  post 'post_action' => "home#post_action"
  get '/post_view/:post_id' => "home#post_view"
  get 'home/post_reply'
  post 'home/post_reply'
  get 'post_view/:post_id' => "home#post_view", as: "post_view"
  get 'post_destroy/:post_id' => "home#post_destroy", as: "post_destroy" 
  get 'post_reply_destroy/:reply_id' => "home#post_reply_destroy"  
  get 'post_update/:post_id' => "home#post_update", as: "post_update"
  post 'post_update_action/:post_id' => "home#post_update_action"
  get 'home/post_result'
  get 'home/mypage'
  
  get '/firstpage', to: 'home#firstpage'
  get '/form_list/:category', to: 'home#form_list', as: "form_list"

  get '/form_view/:form_id', to: 'home#form_view', as: "form_view"
  get '/post_list', to: 'home#post_list', as: "post_list"

  devise_for :users, :skip => [:sessions]
  as :user do
    get 'signin' => 'devise/sessions#new', :as => :home_firstpage_path
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>교메때</title>
  
  <%javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyCMDrWjjhg4Vna6w_SllMqFWdtRWkqDVTs"%>
  <!-- Bootstrap 시작 -->
   
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
  

  
  <% stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css", integrity:"sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r", crossorigin: "anonymous" %>
  <!-- Bootstrap 끝 -->
  
  <!-- Modal  -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  

  
 
  <!-- Template 시작 -->
  <!-- Google fonts styles -->
  <%stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Roboto:400,900italic,900,700italic,700,500italic,500,400italic,300italic,300,100italic,100' %>
  <%stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' %>
  
  <!-- Lifestone styles -->
  <%stylesheet_link_tag "/assets/stylesheets/css/bootstrap.min.css" %>
  <%stylesheet_link_tag  "/assets/stylesheets/css/font-awesome.min.css"%>
  <%stylesheet_link_tag   "/assets/stylesheets/css/ionicons.min.css"%>
    
  <!-- OWL Carousel -->
  <%stylesheet_link_tag "assets/stylesheets/css/owl.carousel.css" %>
  <%stylesheet_link_tag "assets/stylesheets/css/owl.theme.css"%>
  <%stylesheet_link_tag "assets/stylesheets/css/owl.transitions.css" %>
  <%stylesheet_link_tag "assets/stylesheets/css/jquery-smartvimeoembed.css"%>
  <%stylesheet_link_tag "assets/stylesheets/css/flexslider.css"  %>
  <%stylesheet_link_tag "assets/stylesheets/css/style.css"%>
  
  <!-- FAVICON FILES -->
  <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
  <link rel="icon" href="images/favicon.ico" type="image/x-icon">
</head>
<body class="full-page">
  <!--================= Start Preloader ==================-->
    <div class="preloader">
      <div class="spinner">
        <div class="dot1"></div>
        <div class="dot2"></div>
      </div>
    </div>
  <!--================= End Preloader ====================-->
  <div class ="row">
    <div class = "col-md-2">
    <!--================= Start sidebar ==================-->
    <div id="wrapper">
      <div id="sidebar-wrapper">
        <div class="drilldown sidebar-nav mCustomScrollbar">
          <div class="sidebar-brand text-center">                     
            
              <%=link_to (image_tag asset_path('KakaoTalk_20160829_020445928.png'),style:"width:50%;",class: 'img-responsive'), root_path ,method:"get" %>
          
          </div>

          <div class="sidebar-bottom-wrap">
           
            <form id="search_form_1" name="search" method="get" class="search-form_header" action="/home/firstpage_result">
              <i class="fa fa-search submit-wrap" aria-hidden="true" style="color:white;"></i>
              <input type="text" onblur="if (this.value == '') {this.value = 'SEARCH...';}" onfocus="if (this.value == 'SEARCH...') {this.value = '';}" id="search" name="search" value="SEARCH..." class="textboxsearch">
            </form>
          </div>
          
          <div class="drilldown-container">
            <ul class="drilldown-root" style = "text-align: center">                         
              <li class="<%= is_active?(cover_report_path) %>">
                <%= link_to "HOME", cover_report_path , method: 'get'%>
              </li>

              <li class="<%= is_active?(form_list_path(1)) %>">
                <%= link_to "성적정정", form_list_path(1), method: 'get'%>
              </li>
              <li class="<%= is_active?(form_list_path(2)) %>">
                <%= link_to "수강/출석", form_list_path(2), method: 'get'%>
              </li>
              <li class="<%= is_active?(form_list_path(3)) %>">
                <%= link_to "면담요청", form_list_path(3), method: 'get'%>
              </li>
              <li class="<%= is_active?(form_list_path(4)) %>">
                <%= link_to "영어메일", form_list_path(4), method: 'get'%>
              </li>
              <li class="<%= is_active?(form_list_path(5)) %>">
                <%= link_to "기타양식", form_list_path(5), method: 'get'%>
              </li>
              <li class="<%= is_active?(post_list_path) %>">
                <%= link_to "커뮤니티", post_list_path, method: 'get'%>
              </li>
              <li class="<%= is_active?(cover_contact_path) %>">
                <%= link_to "CONTACT", cover_contact_path, method: 'get'%>
              </li>              
            </ul>
          </div>
  
        </div>
      </div>
      </div>
    </div>
    <!--================= End sidebar ==================-->
    <!--================= Start Top Bar ====================-->
      <ul class= "top-nav-bar col-md-12 col-md-offset-1" style="margin-left:150px;">
        <li class= "logo-top">
         <%= link_to (image_tag asset_path('KakaoTalk_20160829_035313826.png'), style:"width:80%;",class: 'img-responsive'), cover_report_path, method: 'get' %>
        </li>
        <% if user_signed_in? %>
          <li class= "top-Btn-2">
            <%= link_to "로그아웃", destroy_user_session_path, method: :delete, data:{confirm: "Are you sure?"},class: "application_link"%>
          </li>
          <li class="user-nickname">
            <%= link_to current_user.nickname, home_mypage_path, method: "get", class: "application_link" %>님
          </li>
        <% else %>
          <li class= "top-Btn-2">
            <%= link_to "로그인 ", new_user_session_path, method:"get", class: "application_link" %>
          </li>
          <li class= "top-Btn-1">
            <%= link_to "회원가입", new_user_registration_path, method:"get", class: "application_link"%>
          </li>
        <% end %>
      </ul>

   
  <!--================= End Top Bar ====================-->
   
   <!--================= TOGGLE MENU ICON STARTS ==================-->
    <a href="#menu-toggle" class="menu-icon" id="menu-toggle"><i class="fa fa-bars"></i></a>
   <!--================= TOGGLE MENU ICON end ==================-->

   <!--================= Start Footer ==================-->
    <!--<footer>
      <div class="container relative">
        <div class="sub-footer"><span class="copyright"> Copyrights © 교메때</span></div>
      </div>
    </footer>-->
  <!--================= End Footer ==================-->
      
  </div>
  
  <!-- Jquery Lib version 1.11.0 -->
  
  <%javascript_include_tag "javascripts/js/jquery.min.js"%>
  <%javascript_include_tag "javascripts/js/bootstrap.min.js" %>
  <%javascript_include_tag "javascripts/js/plugins.js"%>
  <%javascript_include_tag "javascripts/js/main.js"%>
 
 
<%= yield %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</div>
</body>

</html>